config {
    type: "table",
    database: dataform.projectConfig.defaultDatabase,
    schema: "billing_" + dataform.projectConfig.vars.ENV,
    name: "billing_detailed",
    description: "",
    tags: [
        "lifecycle:deactive"
    ]
}

SELECT
  *
FROM
  ${ref(dataform.projectConfig.vars.PROJ_BILL_DUMP, dataform.projectConfig.vars.DATASET_BILL_DUMP, "gcp_billing_export_resource_v1_" + dataform.projectConfig.vars.BILLING_ACCOUNT)}
