config {
    type: "table",
    database: dataform.projectConfig.defaultDatabase,
    schema: "billing_" + dataform.projectConfig.vars.ENV,
    name: "cloud_pricing",
    description: "",
    tags: [
        "stage:to_be_difined",
        "lifecycle:deactive",
        "cloud_pricing"
    ]
}

SELECT
  *
FROM
  ${ref(dataform.projectConfig.vars.PROJ_BILL_DUMP, dataform.projectConfig.vars.DATASET_BILL_DUMP, "cloud_pricing_export")}


