config {
  type: "operations",
  database: dataform.projectConfig.defaultDatabase,
  schema: "billing_" + dataform.projectConfig.vars.ENV,
  name: "model_gemini",
  description: "",
  tags: [
    "lifecycle:deactive"
  ]
}


CREATE OR REPLACE MODEL `${dataform.projectConfig.defaultDatabase}.${"billing_" + dataform.projectConfig.vars.ENV}.model_gemini`
REMOTE WITH CONNECTION `${dataform.projectConfig.defaultDatabase}.${dataform.projectConfig.defaultLocation}.${dataform.projectConfig.vars.GEMINI_CNX}`
OPTIONS(endpoint = 'gemini-2.0-flash-001'); 

-- gemini-2.0-flash-001
-- gemini-2.0-flash-lite-001
-- gemini-1.5-pro-002
-- gemini-1.5-flash-002

