config {
 database: dataform.projectConfig.defaultDatabase,
 schema: "billing_" + dataform.projectConfig.vars.ENV,
 name: "model_gemini",
 description: "",
 tags: [
   "lifecycle:deactive"
 ]
}


CREATE OR REPLACE MODEL `personalhub11.billing_dev.model_gemini`
REMOTE WITH CONNECTION `personalhub11.US.bq_gemini_connection`
OPTIONS(endpoint = 'gemini-2.0-flash-001');

-- gemini-2.0-flash-001
-- gemini-2.0-flash-lite-001
-- gemini-1.5-pro-002
-- gemini-1.5-flash-002

